version: '3'
services:
  oidc-mock-identity-provider-server:
    build: ./oidc/identity-provider-mock/mock-provider-server
    ports:
      - '28200:28200'

  oidc-mongodb-server:
    build: ./oidc/identity-provider-mock
    depends_on:
      - oidc-mock-identity-provider-server
    ports:
      - '27096:27017'
