#!/usr/bin/env bash

set -e

echo '<!-- autogenerated change in README.tmpl.md and README.md of subdirectories -->' > README.md
cat README.tmpl.md >> README.md

for f in */README.md; do (cat "${f}"; echo) >> README.md; done

npx markdown-toc -i README.md