version: '3'
services:
  ldap-server:
    build: ./ldap

  mongodb:
    image: devtools-mongodb-enterprise:${MONGODB_VERSION:-4.4}
    build:
      context: '../enterprise/${MONGODB_VERSION:-4.4}'
      args:
        MONGO_PACKAGE: 'mongodb-enterprise'
        MONGO_REPO: repo.mongodb.com
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    depends_on:
      - ldap-server
    ports:
      - '30017:27017'
    volumes:
      - ./etc/mongod.conf:/etc/mongod.conf:ro
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    command:
      - 'mongod'
      - '--config'
      - '/etc/mongod.conf'
