version: '3'
services:
  mongodb-server-with-mock-oidc-provider:
    build: .
    ports:
      - '27096:27017'
      - '29091:29091'
    environment:
      - OIDC_TOKEN_PAYLOAD_EXPIRES_IN
      # comma-separated list
      - OIDC_TOKEN_PAYLOAD_GROUPS
      - OIDC_TOKEN_PAYLOAD_SUB
      - OIDC_TOKEN_PAYLOAD_AUD
