version: '3'

services:
  mongodb:
    image: devtools-mongodb-enterprise:4.4
    build:
      context: "4.4"
      args:
        MONGO_PACKAGE: "mongodb-enterprise"
        MONGO_REPO: repo.mongodb.com
    ports:
      - "27021:27017"
